### ISSUE TITLE
Unable to connect, possibly missing port number

### ISSUE THREAD

**Issue by OPerepadia** [JGeek00/linkdy#1]
It seems the 'Port' field is not being set correctly when generating the final URL string, because the app is trying to connect using the default HTTP port.

Steps to reproduce:
1. Specify some port number other than 80, e.g. 9090.
2. Press 'Test connection url' button and observe that the port is not present in the URL string.

**Comment by JGeek00** [comment]
Fixed on v0.2.1.

**Comment by OPerepadia** [comment]
The button 'Test connection URL' now opens correct URL. But when trying to connect using the 'Connect' button, there is still an error 'Cannot connect to the server'. And there is nothing showing up in the linkding logs, so it seems the URL might still needs to be fixed for the 'Connect' button as well.

**Comment by JGeek00** [comment]
It will be fixed on the following version to v0.4.0.
